import { IMyData } from './interfaces';

export const APP = 'app';
export const MAIN = 'main';
export const ADMIN = 'admin';
export const NOT_FOUND = 'Element not found';
export const TRAIN = 'train';
export const PLAY = 'play';
export const MAIN_PAGE = 'Main Page';
export const STATISTIC = 'Statistic';
export const MENU_BAR_SELECT = 'menu-bar-select';
export const CORRECT_CARD = 'correct-card';
export const WRONG_NAME = 'wrong-name';
export const NEW_SECTION = 'newSection';
export const NEW_WORD = 'newWord';
export const CATEGORIES = 'Categoies';
export const WORDS = 'Words';
export const ACTIVE = 'active';
export const HIDE = 'hide';
export const TIME_OF_FINAL_IMG = 5000;
export const ZERO = 0;
export const ONE = 1;
export const ZERO_POINT_FIVE = 0.5;
export const ONE_HUNDRED = 100;
export const FOUR = 4;

export const MY_DATA: IMyData = {
  section0: {
    name: 'Action (set A)',
    cards:
    [
      {
        word: 'cry',
        translation: 'плакать',
        img: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'dance',
        translation: 'танцевать',
        img: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'dive',
        translation: 'нырять',
        img: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'draw',
        translation: 'рисовать',
        img: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        img: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'fly',
        translation: 'летать',
        img: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'hug',
        translation: 'обнимать',
        img: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'jump',
        translation: 'прыгать',
        img: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section1: {
    name: 'Action (set B)',
    cards:
    [
      {
        word: 'open',
        translation: 'открывать',
        img: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'play',
        translation: 'играть',
        img: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'point',
        translation: 'указывать',
        img: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'ride',
        translation: 'ездить',
        img: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'run',
        translation: 'бегать',
        img: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'sing',
        translation: 'петь',
        img: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'skip',
        translation: 'прыгать',
        img: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'swim',
        translation: 'плавать',
        img: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section2: {
    name: 'Animal (set A)',
    cards:
    [
      {
        word: 'cat',
        translation: 'кот',
        img: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        img: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'chicken',
        translation: 'курица',
        img: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'dog',
        translation: 'собака',
        img: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'horse',
        translation: 'лошадь',
        img: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'pig',
        translation: 'свинья',
        img: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        img: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'sheep',
        translation: 'овца',
        img: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section3: {
    name: 'Animal (set B)',
    cards:
    [
      {
        word: 'bird',
        translation: 'птица',
        img: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'fish',
        translation: 'рыба',
        img: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'frog',
        translation: 'жаба',
        img: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        img: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'lion',
        translation: 'лев',
        img: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'mouse',
        translation: 'мышь',
        img: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        img: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        img: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section4: {
    name: 'Clothes',
    cards:
    [
      {
        word: 'skirt',
        translation: 'юбка',
        img: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'pants',
        translation: 'брюки',
        img: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'blouse',
        translation: 'блузка',
        img: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'dress',
        translation: 'платье',
        img: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'boot',
        translation: 'ботинок',
        img: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        img: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'coat',
        translation: 'пальто',
        img: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'shoe',
        translation: 'туфли',
        img: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section5: {
    name: 'Emotions',
    cards:
    [
      {
        word: 'sad',
        translation: 'грустный',
        img: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'angry',
        translation: 'сердитый',
        img: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'happy',
        translation: 'счастливый',
        img: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'tired',
        translation: 'уставший',
        img: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        img: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'scared',
        translation: 'испуганный',
        img: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'smile',
        translation: 'улыбка',
        img: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'laugh',
        translation: 'смех',
        img: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section6: {
    name: 'Toys',
    cards:
    [
      {
        word: 'whirligig',
        translation: 'юла',
        img: 'img/whirligig.jpg',
        audioSrc: 'audio/whirligig.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'ball',
        translation: 'мяч',
        img: 'img/ball.jpg',
        audioSrc: 'audio/ball.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'car',
        translation: 'машина',
        img: 'img/car.jpg',
        audioSrc: 'audio/car.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'pistol',
        translation: 'пистолет',
        img: 'img/pistol.jpg',
        audioSrc: 'audio/pistol.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'doll',
        translation: 'кукла',
        img: 'img/doll.jpg',
        audioSrc: 'audio/doll.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'bucket',
        translation: 'ведро',
        img: 'img/bucket.jpg',
        audioSrc: 'audio/bucket.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'shovel',
        translation: 'лопата',
        img: 'img/shovel.jpg',
        audioSrc: 'audio/shovel.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'telephone',
        translation: 'телефон',
        img: 'img/telephone.jpg',
        audioSrc: 'audio/telephone.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
  section7: {
    name: 'Sweetness',
    cards:
    [
      {
        word: 'candy',
        translation: 'конфета',
        img: 'img/candy.jpg',
        audioSrc: 'audio/candy.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'cookies',
        translation: 'печенье',
        img: 'img/cookies.jpg',
        audioSrc: 'audio/cookies.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'ice cream',
        translation: 'мороженое',
        img: 'img/ice cream.jpg',
        audioSrc: 'audio/ice cream.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'cake',
        translation: 'пирожное',
        img: 'img/cake.jpg',
        audioSrc: 'audio/cake.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'chocolate',
        translation: 'шоколад',
        img: 'img/chocolate.jpg',
        audioSrc: 'audio/chocolate.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'halva',
        translation: 'халва',
        img: 'img/halva.jpg',
        audioSrc: 'audio/halva.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'iris',
        translation: 'ирис',
        img: 'img/iris.jpg',
        audioSrc: 'audio/iris.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
      {
        word: 'gum',
        translation: 'жвачка',
        img: 'img/gum.jpg',
        audioSrc: 'audio/gum.mp3',
        hit: 0,
        miss: 0,
        train: 0,
      },
    ],
  },
};
